{% set version = "6.0" %}

package:
  name: cx_freeze
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cx_Freeze/cx_Freeze-{{ version }}.tar.gz
  sha256: ca81d8e5f3da9eace9dc20e1c4250b69d2b096f63c6eb5c3e073c4d3df7ceb18
  #patches:
    # python 3.7 fix
    #- 0001-Update-freezer.py-395.patch

build:
  number: 0
  script:
    # https://github.com/anthony-tuininga/cx_Freeze/issues/407
    #- copy %RECIPE_DIR%\cxfreeze-postinstall .  # [win]
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - cx_Freeze

about:
  home: https://anthony-tuininga.github.io/cx_Freeze
  license: Python Software Foundation
  license_family: PSF
  license_file: README.md
  summary: create standalone executables from Python scripts

extra:
  recipe-maintainers:
    - jschueller
